#!/bin/bash
echo "ALX"
^C
[A[C[D[C[C[D[1;2A[D[C[3~[3~cd ..
[C
[1;2A[1;2A[1;2A[1;2A[1;2B[1;6A[1;6A[1;6A[B[B[B[Bpwd
cd ..
[C[D[C[D[D[D[D


[A[A[A
root@062e85b81847:/alx-pre_course/0x01-git/bash#
[D[D
root@062e85b81847:/alx-pre_course/0x01-git/bash# clear
root@062e85b81847:/alx-pre_course/0x01-git/bash# cd clear
